import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
        <Navbar />
        <body className={inter.className}>{children}</body>
    </>
  );
}
